version: '3.3'
services:
  postgres:
    image: postgres:9.3-alpine
    restart: always
    ports:
      - 5432
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=test_hodor
  rabbitmq:
    image: rabbitmq:3.6-management-alpine
    restart: always
    volumes:
      - ./docker/rabbitmq:/etc/rabbitmq
    ports:
      - 5672
      - 15672
    hostname: rabbitmq
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./docker/php/entrypoint.sh:/usr/local/bin/entrypoint.sh
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - .:/hodor
      - ~/.composer/:/root/.composer
    depends_on:
      - postgres
      - rabbitmq
